### PR TITLE
Add some new snowflakes, thanks to @shadowkyogre

### PR DESCRIPTION
**Pull request by ethus3h**

### CODE REVIEW

**Comment by soreau** [comment]
To be honest, my first thought about the sheer number of additions here is a bit ridiculous. This would simply install all of these additional texture files? It seems to me that users will never know they are there and it will only increase installation size.

Instead, I propose we change the default textures to the very 'best', most polished we can find. Then the user doesn't have to do anything.

If we decide to add these additional textures, I would prefer if the list is distilled significantly. Users have their own tastes and can easily experiment with images of their choice.

@ShadowKyogre Thoughts?

**Comment by ethus3h** [comment]
Hmm, that makes sense. Maybe better to not include any non-default textures in the distribution then; I'll close this then. (I'll make a separate repo for them, since I do like having them available, but that way they won't be needlessly packaged as part of compiz-reloaded.) Thanks for the idea @soreau! :)

**Comment by ShadowKyogre** [comment]
Sorry for the delayed reply here! Got unexpectedly flooded with some IRL stuff.

My thoughts are pretty much the same on this. The most polished versions of the textures should be the one in the PR (( ideally all at the same resolution since I have the source *.ora laying somewhere on my drive )).

**Comment by ethus3h** [comment]
(To follow up, I've packaged the extra snowflakes as compiz-extra-snowflake-textures, available in my overlay https://github.com/ethus3h/wreathe-overlay (note that this assumes the patch at https://github.com/compiz-reloaded/compiz-plugins-experimental/issues/9#issuecomment-249476994 is applied, and will have one redundant snowflake and one missing snowflake if installed without that patch))

**Pull request closed without merging**
