### PR TITLE
earth: Provide sample of appropriate cloud map

### PR DESCRIPTION
**Pull request by ethus3h**
As protection against the event of the associated URL going down, this is a sample of what this file is expected to contain.

This file was retrieved from http://home.megapass.co.kr/~holywatr/cloud_data/clouds_2048.jpg on 2017 April 17a18.

### CODE REVIEW

**Comment by Eignar17** [comment]
is code similar of [https://github.com/matijaskala/compiz-earth/issues/5](url) is not bat idea interesant from to fix cloud @matijaskala

**Comment by Eignar17** [comment]
@ethus3h  and generate problems fox textures https://github.com/matijaskala/compiz-earth/issues/4#issuecomment-294377626

**Comment by ethus3h** [comment]
@Eignar17, it looks like the associated patches are already included in the copy of earth that was upstreamed into this plugin :)

**Comment by soreau** [comment]
https://raw.githubusercontent.com/compiz-reloaded/compiz-plugins-experimental/master/images/earth/clouds.png already exists as part of the repository so I don't think this is necessary.

**Comment by ethus3h** [comment]
@soreau, The two files look quite different. Can the clouds.png file be used as a drop-in replacement for clouds_2048.jpg?

**Comment by Eignar17** [comment]
@soreau  is add new code ? 
[https://github.com/matijaskala/compiz-earth/pull/6](url)

@ethus3h is your code not good idea

**Comment by soreau** [comment]
@ethus3h yes, they do look quite different but they are interchangable

**Comment by ethus3h** [comment]
Cool, thanks @soreau!

**Comment by ethus3h** [comment]
@Eignar17 Oh, this isn't any code, just a new image. It's not a bad idea so much as it's just redundant.

**Comment by Eignar17** [comment]
ok sorry

**Pull request closed without merging**
