### PR TITLE
update translate spanish and add new icon analyph

### PR DESCRIPTION
**Pull request by Eignar17**

### CODE REVIEW

**Comment by Eignar17** [comment]
@soreau  view new icon

**Comment by soreau** [comment]
I was giving others the opportunity to vote on the new icon and it seems like 3D glasses might be a good idea for an icon. Are you able to produce something like [this](https://goo.gl/images/bhjG6v) maybe with a cube?

So far as the es.po translation goes, can you put that in a separate pull request?

**Comment by Eignar17** [comment]
or https://github.com/Eignar17/compiz-fusion-icons/blob/master/oxygen/plugin-anaglyph.svg

@matijaskala work in port to 0.8 https://github.com/matijaskala/compiz-plugin-stereo3d
plugin Similar to anaglyph and add to new effect stereo and similarity icon is my problem

**Comment by Eignar17** [comment]
@soreau is create new icons similary to classic icon animationplus or animationsim ?

**Comment by soreau** [comment]
https://github.com/Eignar17/compiz-fusion-icons/blob/master/oxygen/plugin-anaglyph.svg seems to be a blank vertical line?

**Comment by Eignar17** [comment]
I don't understand.

**Comment by soreau** [comment]
https://i.imgur.com/mRtiyT0.png

**Comment by soreau** [comment]
We were wanting to know if you could provide an icon something like [this](https://ae01.alicdn.com/kf/HTB1rveTc2uSBuNkHFqDq6xfhVXa5/100-pairs-Universal-Paper-Anaglyph-3D-Glasses-Paper-3D-Glasses-View-Anaglyph-Red-Cyan-Red-Blue.jpg_640x640.jpg)?

**Comment by Eignar17** [comment]
https://imgur.com/a/P8UOIWu

**Comment by soreau** [comment]
Well even the .svg file text is https://raw.githubusercontent.com/Eignar17/compiz-fusion-icons/master/oxygen/plugin-anaglyph.svg

**Comment by Eignar17** [comment]
https://github.com/Eignar17/compiz-fusion-icons/blob/master/tango/plugin-anaglyph.svg

**Comment by Eignar17** [comment]
or https://github.com/Eignar17/compiz-fusion-icons/blob/master/tango/plugin-anaglyph.svg

**Comment by Eignar17** [comment]
ok add new icon and new translate

**Pull request closed without merging**
