### PR TITLE
Add boing plugin roach

### PR DESCRIPTION
**Pull request by Eignar17**

### CODE REVIEW

**Comment by soreau** [comment]
Thanks for the patch work but I don't think we want a roach plugin in compiz-reloaded. Boing might be ok, but it needs to be split into a separate patch.

**Comment by ethus3h** [comment]
Idea: maybe there could be a compiz-plugins-community repository or something where plugins that aren't included in the main distribution go.

**Comment by Eignar17** [comment]
@soreau remove roach

**Comment by soreau** [comment]
"src/Makefile.am:3: error: required directory src/roach does not exist"
also can you update the ccsm patch?

**Comment by Eignar17** [comment]
@soreau is update sorry

**Pull request closed without merging**
