### PR TITLE
Fill in holes in snowflake texture (work done by @ShadowKyogre).

### PR DESCRIPTION
**Pull request by ethus3h**
This doesn't need to be merged if you don't want it, so I'll close it right away, but it lets you see what my patch at https://github.com/compiz-reloaded/compiz-plugins-experimental/issues/9#issuecomment-249476994 changes. Personally I think this is an improvement over the current default snowflake texture.

### CODE REVIEW

**Comment by ethus3h** [comment]
On further reflection, I can't really think of any downsides to this change, so I'll leave it open since I do think it would make sense to merge.

**Comment by soreau** [comment]
Do you have before-and-after screenshots to show what this actually fixes and/or steps to reproduce the problem? If there is a texture that doesn't work well with some settings, it might point to an underlying issue with how the plugin handles loading and rendering of the texture.

**Comment by ethus3h** [comment]
Sure! See how the one on the left has some pixels missing, making the background show through?
screenshot_2016 10 18_17 41 22

**Comment by ethus3h** [comment]
Actually, maybe it's not so much that they're missing as that they aren't white…

**Comment by soreau** [comment]
Ah, so there are actually pixel artifacts in the stock image, that both snow and elements use by default. Thanks for clearing that up.

**Comment by ethus3h** [comment]
Certainly, although I think that's only used by snow by default IIRC; I think elements has its own default textures

**Pull request merged**
